import type { Exercise, WorkoutDay, PlanVariant } from './types';

export const EXERCISES: Record<string, Exercise> = {
  // CHEST
  bench_press: {
    id: 'bench_press',
    name: 'Barbell Bench Press',
    muscleGroup: 'chest',
    description: 'The king of chest exercises. Flat bench with barbell.',
    setsMin: 4, setsMax: 6, repsMin: 6, repsMax: 12,
    restSeconds: 90,
    formTip: 'Keep shoulder blades retracted, arch slightly, bar to lower chest.',
  },
  incline_press: {
    id: 'incline_press',
    name: 'Incline Dumbbell Press',
    muscleGroup: 'chest',
    description: 'Upper chest focus at 30-45 degree angle.',
    setsMin: 3, setsMax: 4, repsMin: 8, repsMax: 12,
    restSeconds: 75,
    formTip: 'Control the descent, squeeze at the top.',
  },
  dumbbell_flyes: {
    id: 'dumbbell_flyes',
    name: 'Dumbbell Flyes',
    muscleGroup: 'chest',
    description: 'Isolation for chest with wide arc motion.',
    setsMin: 3, setsMax: 4, repsMin: 10, repsMax: 15,
    restSeconds: 60,
    formTip: 'Slight bend in elbows throughout. Feel the stretch.',
  },
  cable_crossover: {
    id: 'cable_crossover',
    name: 'Cable Crossover',
    muscleGroup: 'chest',
    description: 'Cable isolation for inner chest definition.',
    setsMin: 3, setsMax: 4, repsMin: 12, repsMax: 15,
    restSeconds: 60,
    formTip: 'Cross hands at the bottom, squeeze hard.',
  },
  dips: {
    id: 'dips',
    name: 'Weighted Dips',
    muscleGroup: 'chest',
    description: 'Compound movement for lower chest and triceps.',
    setsMin: 3, setsMax: 4, repsMin: 8, repsMax: 12,
    restSeconds: 90,
    formTip: 'Lean slightly forward to target chest.',
  },
  // BACK
  deadlift: {
    id: 'deadlift',
    name: 'Barbell Deadlift',
    muscleGroup: 'back',
    description: 'The ultimate posterior chain builder.',
    setsMin: 4, setsMax: 5, repsMin: 4, repsMax: 8,
    restSeconds: 120,
    formTip: 'Bar over mid-foot, chest up, push floor away.',
  },
  barbell_row: {
    id: 'barbell_row',
    name: 'Barbell Bent-Over Row',
    muscleGroup: 'back',
    description: "Arnold's favorite back thickness builder.",
    setsMin: 4, setsMax: 5, repsMin: 6, repsMax: 12,
    restSeconds: 90,
    formTip: 'Pull to lower abs, elbows back, squeeze at top.',
  },
  pullups: {
    id: 'pullups',
    name: 'Wide-Grip Pull-Ups',
    muscleGroup: 'back',
    description: 'V-taper builder. Use weight belt when strong.',
    setsMin: 4, setsMax: 5, repsMin: 6, repsMax: 12,
    restSeconds: 90,
    formTip: 'Full stretch at bottom, pull to chest level.',
  },
  cable_row: {
    id: 'cable_row',
    name: 'Seated Cable Row',
    muscleGroup: 'back',
    description: 'Mid-back thickness with constant tension.',
    setsMin: 3, setsMax: 4, repsMin: 10, repsMax: 15,
    restSeconds: 75,
    formTip: 'Keep torso upright, squeeze shoulder blades.',
  },
  lat_pulldown: {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    muscleGroup: 'back',
    description: 'Lat width builder. Wide or close grip variations.',
    setsMin: 3, setsMax: 4, repsMin: 10, repsMax: 12,
    restSeconds: 75,
    formTip: 'Lean back slightly, pull to upper chest.',
  },
  // SHOULDERS
  overhead_press: {
    id: 'overhead_press',
    name: 'Barbell Overhead Press',
    muscleGroup: 'shoulders',
    description: 'The shoulder mass builder. Standing or seated.',
    setsMin: 4, setsMax: 5, repsMin: 6, repsMax: 12,
    restSeconds: 90,
    formTip: 'Bar in front, elbows slightly forward.',
  },
  dumbbell_shoulder_press: {
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    muscleGroup: 'shoulders',
    description: 'Seated dumbbell press for full shoulder development.',
    setsMin: 3, setsMax: 4, repsMin: 8, repsMax: 12,
    restSeconds: 75,
    formTip: 'Full range of motion, control the descent.',
  },
  lateral_raises: {
    id: 'lateral_raises',
    name: 'Lateral Raises',
    muscleGroup: 'shoulders',
    description: 'Medial deltoid isolation for wide shoulder look.',
    setsMin: 4, setsMax: 5, repsMin: 12, repsMax: 20,
    restSeconds: 45,
    formTip: 'Slight forward tilt of dumbbells, lead with elbows.',
  },
  front_raises: {
    id: 'front_raises',
    name: 'Front Raises',
    muscleGroup: 'shoulders',
    description: 'Anterior deltoid isolation.',
    setsMin: 3, setsMax: 4, repsMin: 12, repsMax: 15,
    restSeconds: 60,
    formTip: 'Alternate arms, controlled movement.',
  },
  bent_over_laterals: {
    id: 'bent_over_laterals',
    name: 'Bent-Over Lateral Raises',
    muscleGroup: 'shoulders',
    description: 'Rear deltoid development for complete shoulder roundness.',
    setsMin: 3, setsMax: 4, repsMin: 12, repsMax: 20,
    restSeconds: 60,
    formTip: 'Bend 45°, lift to shoulder height.',
  },
  // BICEPS
  barbell_curl: {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    muscleGroup: 'biceps',
    description: 'The classic mass builder for biceps.',
    setsMin: 4, setsMax: 5, repsMin: 8, repsMax: 12,
    restSeconds: 75,
    formTip: 'Keep elbows pinned, full range of motion.',
  },
  incline_curl: {
    id: 'incline_curl',
    name: 'Incline Dumbbell Curl',
    muscleGroup: 'biceps',
    description: 'Extended stretch for biceps peak development.',
    setsMin: 3, setsMax: 4, repsMin: 10, repsMax: 12,
    restSeconds: 60,
    formTip: 'Let arms hang fully, supinate at top.',
  },
  concentration_curl: {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    muscleGroup: 'biceps',
    description: "Arnold's peak builder. The best isolation movement.",
    setsMin: 3, setsMax: 4, repsMin: 10, repsMax: 15,
    restSeconds: 45,
    formTip: 'Elbow braced on inner thigh, full squeeze at top.',
  },
  // TRICEPS
  close_grip_bench: {
    id: 'close_grip_bench',
    name: 'Close-Grip Bench Press',
    muscleGroup: 'triceps',
    description: 'The best compound triceps mass builder.',
    setsMin: 4, setsMax: 5, repsMin: 6, repsMax: 12,
    restSeconds: 90,
    formTip: 'Shoulder-width grip, tuck elbows tight.',
  },
  skull_crushers: {
    id: 'skull_crushers',
    name: 'Skull Crushers',
    muscleGroup: 'triceps',
    description: 'EZ bar or straight bar for long head development.',
    setsMin: 3, setsMax: 4, repsMin: 8, repsMax: 12,
    restSeconds: 75,
    formTip: 'Lower to forehead, elbows in tight.',
  },
  pushdowns: {
    id: 'pushdowns',
    name: 'Cable Pushdowns',
    muscleGroup: 'triceps',
    description: 'Cable isolation for tricep definition.',
    setsMin: 3, setsMax: 4, repsMin: 12, repsMax: 15,
    restSeconds: 60,
    formTip: 'Full extension, squeeze at bottom, elbows fixed.',
  },
  // LEGS
  squat: {
    id: 'squat',
    name: 'Barbell Back Squat',
    muscleGroup: 'legs',
    description: 'The king of all exercises. Full leg development.',
    setsMin: 5, setsMax: 6, repsMin: 6, repsMax: 12,
    restSeconds: 120,
    formTip: 'Chest up, knees track toes, go below parallel.',
  },
  leg_press: {
    id: 'leg_press',
    name: 'Leg Press',
    muscleGroup: 'legs',
    description: 'Heavy quad builder with reduced spinal load.',
    setsMin: 4, setsMax: 5, repsMin: 10, repsMax: 20,
    restSeconds: 90,
    formTip: "Full range, don't lock knees at top.",
  },
  leg_curl: {
    id: 'leg_curl',
    name: 'Lying Leg Curl',
    muscleGroup: 'legs',
    description: 'Hamstring isolation.',
    setsMin: 3, setsMax: 4, repsMin: 10, repsMax: 15,
    restSeconds: 60,
    formTip: 'Full extension, curl to maximum contraction.',
  },
  leg_extension: {
    id: 'leg_extension',
    name: 'Leg Extension',
    muscleGroup: 'legs',
    description: 'Quad isolation and separation.',
    setsMin: 3, setsMax: 4, repsMin: 12, repsMax: 20,
    restSeconds: 60,
    formTip: 'Squeeze hard at top, controlled descent.',
  },
  lunges: {
    id: 'lunges',
    name: 'Barbell Lunges',
    muscleGroup: 'legs',
    description: 'Full quad and glute development with balance work.',
    setsMin: 3, setsMax: 4, repsMin: 10, repsMax: 15,
    restSeconds: 75,
    formTip: 'Long stride, back knee near floor.',
  },
  calf_raises: {
    id: 'calf_raises',
    name: 'Standing Calf Raises',
    muscleGroup: 'legs',
    description: 'Calf mass builder. Arnold trained calves obsessively.',
    setsMin: 5, setsMax: 6, repsMin: 15, repsMax: 25,
    restSeconds: 45,
    formTip: 'Full stretch at bottom, full contraction at top.',
  },
};

export const WORKOUT_DAYS: Record<PlanVariant, WorkoutDay[]> = {
  beginner: [
    {
      dayNumber: 1,
      name: 'Chest & Back',
      muscleGroups: ['chest', 'back'],
      exercises: [
        EXERCISES.bench_press,
        EXERCISES.barbell_row,
        EXERCISES.incline_press,
        EXERCISES.lat_pulldown,
        EXERCISES.dumbbell_flyes,
        EXERCISES.cable_row,
      ],
    },
    {
      dayNumber: 2,
      name: 'Shoulders & Arms',
      muscleGroups: ['shoulders', 'biceps', 'triceps'],
      exercises: [
        EXERCISES.overhead_press,
        EXERCISES.barbell_curl,
        EXERCISES.close_grip_bench,
        EXERCISES.lateral_raises,
        EXERCISES.incline_curl,
        EXERCISES.pushdowns,
      ],
    },
    {
      dayNumber: 3,
      name: 'Legs & Calves',
      muscleGroups: ['legs'],
      exercises: [
        EXERCISES.squat,
        EXERCISES.leg_press,
        EXERCISES.leg_curl,
        EXERCISES.leg_extension,
        EXERCISES.calf_raises,
      ],
    },
  ],
  classic: [
    {
      dayNumber: 1,
      name: 'Chest & Back',
      muscleGroups: ['chest', 'back'],
      exercises: [
        EXERCISES.bench_press,
        EXERCISES.barbell_row,
        EXERCISES.incline_press,
        EXERCISES.pullups,
        EXERCISES.dumbbell_flyes,
        EXERCISES.cable_row,
        EXERCISES.cable_crossover,
        EXERCISES.lat_pulldown,
      ],
    },
    {
      dayNumber: 2,
      name: 'Shoulders & Arms',
      muscleGroups: ['shoulders', 'biceps', 'triceps'],
      exercises: [
        EXERCISES.overhead_press,
        EXERCISES.barbell_curl,
        EXERCISES.close_grip_bench,
        EXERCISES.lateral_raises,
        EXERCISES.incline_curl,
        EXERCISES.skull_crushers,
        EXERCISES.bent_over_laterals,
        EXERCISES.concentration_curl,
        EXERCISES.pushdowns,
      ],
    },
    {
      dayNumber: 3,
      name: 'Legs & Calves',
      muscleGroups: ['legs'],
      exercises: [
        EXERCISES.squat,
        EXERCISES.leg_press,
        EXERCISES.leg_curl,
        EXERCISES.leg_extension,
        EXERCISES.lunges,
        EXERCISES.calf_raises,
      ],
    },
  ],
  advanced: [
    {
      dayNumber: 1,
      name: 'Chest & Back (AM)',
      muscleGroups: ['chest', 'back'],
      exercises: [
        EXERCISES.bench_press,
        EXERCISES.barbell_row,
        EXERCISES.incline_press,
        EXERCISES.pullups,
        EXERCISES.dumbbell_flyes,
        EXERCISES.cable_row,
        EXERCISES.dips,
        EXERCISES.cable_crossover,
        EXERCISES.lat_pulldown,
        EXERCISES.deadlift,
      ],
    },
    {
      dayNumber: 2,
      name: 'Shoulders & Arms (AM)',
      muscleGroups: ['shoulders', 'biceps', 'triceps'],
      exercises: [
        EXERCISES.overhead_press,
        EXERCISES.dumbbell_shoulder_press,
        EXERCISES.barbell_curl,
        EXERCISES.close_grip_bench,
        EXERCISES.lateral_raises,
        EXERCISES.incline_curl,
        EXERCISES.skull_crushers,
        EXERCISES.front_raises,
        EXERCISES.concentration_curl,
        EXERCISES.pushdowns,
        EXERCISES.bent_over_laterals,
      ],
    },
    {
      dayNumber: 3,
      name: 'Legs & Calves (AM)',
      muscleGroups: ['legs'],
      exercises: [
        EXERCISES.squat,
        EXERCISES.leg_press,
        EXERCISES.leg_curl,
        EXERCISES.leg_extension,
        EXERCISES.lunges,
        EXERCISES.calf_raises,
      ],
    },
  ],
};

export const ARNOLD_QUOTES: string[] = [
  "The last three or four reps is what makes the muscle grow. This area of pain divides a champion from someone who is not a champion.",
  "If you want to turn a vision into reality, you have to give 100% and never stop believing in your dream.",
  "Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.",
  "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it, as long as you really believe 100 percent.",
  "Just like in bodybuilding, failure is also a necessary experience for growth in our own lives, for if we're never tested to our limits, how will we know how strong we really are?",
  "Bodybuilding is much like any other sport. To be successful, you must dedicate yourself 100% to your training, diet and mental approach.",
  "For me, life is continuously being hungry. The meaning of life is not simply to exist, to survive, but to move ahead, to go up, to achieve, to conquer.",
  "Pain makes me grow. Growing is what I want. Therefore, for me pain is pleasure.",
  "It's simple, if it jiggles, it's fat.",
  "Training gives us an outlet for suppressed energies created by stress and thus tones the spirit just as exercise conditions the body.",
  "I don't walk away from things that I think are unfinished.",
  "What we face may look insurmountable. But I learned something from all those years of training and competing. I learned something from all those sets and reps when I didn't think I could lift another ounce of weight. What I learned is that we are always stronger than we know.",
  "Everybody pities the weak; jealousy you have to earn.",
  "The worst thing I can be is the same as everybody else. I hate that.",
  "Money doesn't make you happy. I now have $50 million but I was just as happy when I had $48 million.",
  "I knew I was a winner back in the late sixties. I knew I was destined for great things. People will say that kind of thinking is totally immodest. I agree. It was totally immodest. I needed that arrogance, that cockiness, to carry me through.",
  "You can have results or excuses, not both.",
  "The resistance that you fight physically in the gym and the resistance that you fight in life can only build a strong character.",
];

export function getRandomArnoldQuote(): string {
  return ARNOLD_QUOTES[Math.floor(Math.random() * ARNOLD_QUOTES.length)];
}

export const MUSCLE_GROUP_COLORS: Record<string, string> = {
  chest: 'bg-red-900/40 text-red-300 border-red-800',
  back: 'bg-blue-900/40 text-blue-300 border-blue-800',
  shoulders: 'bg-yellow-900/40 text-yellow-300 border-yellow-800',
  biceps: 'bg-purple-900/40 text-purple-300 border-purple-800',
  triceps: 'bg-pink-900/40 text-pink-300 border-pink-800',
  legs: 'bg-green-900/40 text-green-300 border-green-800',
  core: 'bg-orange-900/40 text-orange-300 border-orange-800',
};

export const PLAN_DESCRIPTIONS: Record<PlanVariant, string> = {
  beginner: "Arnold's Foundation Program — 3 days/week, full body focus",
  classic: "The Classic Arnold Split — 3 days/week, double split intensity",
  advanced: "The Golden Era Advanced Split — 6 days/week, 2-a-day training",
};
